### ISSUE TITLE
Add support for logbook integration

### ISSUE THREAD

**Issue by deviceclassesadmin** [S2Innovation/conf-s2i-panic-solaris#1]
The script should add elogsender receiver to alarms.
Format of action is:
- [x] `ACTION(alarm:command,alarm/ctl/elogsnd1/create_entry,$MESSAGE,$NAME,$DESCRIPTION,{subsystem},{level},{stage},{logbook_name})`

- [x] {subsystem} should match subsystem into elog subsystems: `ARCH, CTL, DIA, EL, MAG, MECH, OPT, PSS, RAD, RF, VAC, WAT`
- [x] {level} should match ALARM as `Problem` and other as `Report`
- [x] {stage} should be `Operation`
- [x] {logbook_name} should be either `Storage Ring` or `Injector`
- [x] test above
- [x] merge into devel

**Comment by piogor** [comment]
All tests are passed. This part of script is read.
